module.exports = {
  apps: [
    {
      name: "admin",
      cwd: "./admin",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_file: "./logs/admin.log",
      out_file: "./logs/admin-out.log",
      error_file: "./logs/admin-error.log",
      time: true,
    },
    {
      name: "frontdesk",
      cwd: "./frontdesk",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3002,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_file: "./logs/frontdesk.log",
      out_file: "./logs/frontdesk-out.log",
      error_file: "./logs/frontdesk-error.log",
      time: true,
    },
    {
      name: "driver",
      cwd: "./driver",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_file: "./logs/driver.log",
      out_file: "./logs/driver-out.log",
      error_file: "./logs/driver-error.log",
      time: true,
    },
    {
      name: "guest",
      cwd: "./guest",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3004,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_file: "./logs/guest.log",
      out_file: "./logs/guest-out.log",
      error_file: "./logs/guest-error.log",
      time: true,
    },
    {
      name: "super-admin",
      cwd: "./super-admin",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3005,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_file: "./logs/super-admin.log",
      out_file: "./logs/super-admin-out.log",
      error_file: "./logs/super-admin-error.log",
      time: true,
    },
    {
      name: "server",
      cwd: "./server",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      log_file: "./logs/server.log",
      out_file: "./logs/server-out.log",
      error_file: "./logs/server-error.log",
      time: true,
    },
  ],
};
